@startuml zinbeijett

zinbeijett <--> engine
zinbeijett <--> speak
zinbeijett <--> tweet

zinbeijett : ライセンス情報
zinbeijett : ヘルプ情報
zinbeijett : スタートページ
zinbeijett : バージョン情報

engine : 全文検索(=~)
engine : 全文検索(match)
engine : AND検索
engine : NOT検索
engine : OR検索
engine : メールアドレス検索
engine : GC表示
engine : 作成者情報
engine : 文字列カウント
engine : タイトル表示(RSS)
engine : タイトル表示(feedjira)
engine : サマリー表示(feedjira)
engine : カレンダー(指定した暦)(Pycall)
engine : カレンダー(今の暦)(Pycall)

speak : 対話的プログラム(zinbeiwから機能移植)
speak : 対話的プログラム(Tabで入力補完追加)

tweet : Twitter登録ユーザ(つぶやき機能)
tweet : Twitter登録ユーザ(情報表示)

@enduml